export const themes = {
  HarryPotter: {
    title: "Harry Potter",
    names: [
      "Harry Potter",
      "Hermione Granger",
      "Ron Weasley",
      "Luna Lovegood",
      "Dobby",
      "Albus Dumbledore",
      "Sirius Black",
      "Remus Lupin",
      "Hagrid",
    ],
    image: require("../assets/harry-potter.jpg"),
  },
  PopSingers: {
    title: "Pop singers",
    names: [
      "Taylor Swift",
      "Lady Gaga",
      "Ed Sheeran",
      "Shawn Mendes",
      "Ariana Grande",
      "Dua Lipa",
      "Justin Bieber",
      "Adele",
    ],

    image: require("../assets/pop-singer.jpg"),
  },
  TheOffice: {
    title: "The Office",
    names: [
      "Michael Scott",
      "Dwight Schrute",
      "Pam Beesly",
      "Jim Halpert",
      "Oscar Martinez",
      "Kevin Malone",
      "Angela Martin",
      "Andy Bernard",
      "Stanley Hudson",
      "Ryan Howard",
      "Kelly Kapoor",
    ],
    image: require("../assets/the-office.jpg"),
  },
  Marvel: {
    title: "Marvel",
    names: [
      "Peter Parker",
      "Bruce Banner",
      "Tony Stark",
      "T'Challa",
      "Dr. Otto Octavius",
      "Frank Castle",
      "Doctor Strange",
      "Natasha Romanoff",
      "Jean Grey",
    ],
    image: require("../assets/marvel.jpg"),
  },
  StarWars: {
    title: "Star Wars",
    names: [
      "Luke Skywalker",
      "Anakin Skywalker",
      "Obi-Wan Kenobi",
      "Princess Leia",
      "Han Solo",
      "Yoda",
      "Chewbacca",
      "Jar Jar",
    ],
    image: require("../assets/star-wars.jpg"),
  },
  ModernFamily: {
    title: "Modern Family",
    names: [
      "Haley Dunphy",
      "Phil Dunphy",
      "Alex Dunphy",
      "Gloria Delgado-Pritchett",
      "Lily Tucker-Pritchett",
      "Claire Dunphy",
      "Luke Dunphy",
      "Joe Pritchett",
      "Cameron Tucker",
      "Mitchell Pritchett",
      "Manny Delgado",
      "Jay Pritchett",
    ],
    image: require("../assets/modern-family.jpg"),
  },
};
